---
# Deploy application to remote server
- hosts: remote
  become: no
  gather_facts: no
  vars:
    release_date: "{{ lookup('env','RELEASE_DATE') }}"
    deploy_dir: "/usr/share/nginx/html/jenkins/tanttws2/deploy"
    keep_releases: "{{ lookup('env','KEEP_RELEASES') | default(5) }}"
  environment:
    PYTHONPATH: ""

  tasks:
    # Create deployment directory structure
    - name: Create deployment directory
      raw: mkdir -p "{{ deploy_dir }}" && chmod 755 "{{ deploy_dir }}"

    - name: Create release directory
      raw: mkdir -p "{{ deploy_dir }}/{{ release_date }}" && chmod 755 "{{ deploy_dir }}/{{ release_date }}"

    # Upload index.html from local deploy/{{ release_date }}
    - name: Copy index.html from local to remote (/tmp)
      raw: |
        # Copy file from local workspace to remote
        cat > /tmp/index.html << 'EOF'
        {{ lookup('file', 'deploy/' ~ release_date ~ '/index.html') }}
        EOF
        chmod 644 /tmp/index.html
        echo "✅ Copied file to /tmp/index.html"
      ignore_errors: yes

    - name: Copy index.html from /tmp into release directory
      raw: |
        if [ -f "/tmp/index.html" ]; then
          cat /tmp/index.html > "{{ deploy_dir }}/{{ release_date }}/index.html"
          chmod 644 "{{ deploy_dir }}/{{ release_date }}/index.html"
          echo "✅ Copied to release directory"
        else
          echo "❌ /tmp/index.html not found"
          exit 1
        fi
      register: copy_result
      ignore_errors: yes

    - name: Copy index.html into app directory (for direct access)
      raw: |
        if [ -f "/tmp/index.html" ]; then
          mkdir -p "/usr/share/nginx/html/jenkins/tanttws2/app"
          cat /tmp/index.html > "/usr/share/nginx/html/jenkins/tanttws2/app/index.html"
          chmod 644 "/usr/share/nginx/html/jenkins/tanttws2/app/index.html"
          echo "✅ Copied to app directory"
        else
          echo "❌ /tmp/index.html not found"
        fi
      ignore_errors: yes

        # Upload assets by folder (split to avoid ARG_MAX)
    - name: Upload CSS to release and app directories
      raw: |
        cat > /tmp/css.tgz.b64 << 'EOF'
        {{ lookup('pipe', 'tar -C "deploy/' ~ release_date ~ '" -czf - css 2>/dev/null | base64') }}
        EOF
        if [ -s /tmp/css.tgz.b64 ]; then
          base64 -d /tmp/css.tgz.b64 > /tmp/css.tgz || true
          mkdir -p "{{ deploy_dir }}/{{ release_date }}" "/usr/share/nginx/html/jenkins/tanttws2/app"
          tar -xzf /tmp/css.tgz -C "{{ deploy_dir }}/{{ release_date }}" || true
          tar -xzf /tmp/css.tgz -C "/usr/share/nginx/html/jenkins/tanttws2/app" || true
          rm -f /tmp/css.tgz /tmp/css.tgz.b64
          echo "✅ CSS extracted"
        else
          echo "ℹ️ No CSS folder locally, skip"
        fi
      ignore_errors: yes

    - name: Upload JS to release and app directories
      raw: |
        cat > /tmp/js.tgz.b64 << 'EOF'
        {{ lookup('pipe', 'tar -C "deploy/' ~ release_date ~ '" -czf - js 2>/dev/null | base64') }}
        EOF
        if [ -s /tmp/js.tgz.b64 ]; then
          base64 -d /tmp/js.tgz.b64 > /tmp/js.tgz || true
          mkdir -p "{{ deploy_dir }}/{{ release_date }}" "/usr/share/nginx/html/jenkins/tanttws2/app"
          tar -xzf /tmp/js.tgz -C "{{ deploy_dir }}/{{ release_date }}" || true
          tar -xzf /tmp/js.tgz -C "/usr/share/nginx/html/jenkins/tanttws2/app" || true
          rm -f /tmp/js.tgz /tmp/js.tgz.b64
          echo "✅ JS extracted"
        else
          echo "ℹ️ No JS folder locally, skip"
        fi
      ignore_errors: yes

    - name: Upload Images to release and app directories
      raw: |
        cat > /tmp/images.tgz.b64 << 'EOF'
        {{ lookup('pipe', 'tar -C "deploy/' ~ release_date ~ '" -czf - images 2>/dev/null | base64') }}
        EOF
        if [ -s /tmp/images.tgz.b64 ]; then
          base64 -d /tmp/images.tgz.b64 > /tmp/images.tgz || true
          mkdir -p "{{ deploy_dir }}/{{ release_date }}" "/usr/share/nginx/html/jenkins/tanttws2/app"
          tar -xzf /tmp/images.tgz -C "{{ deploy_dir }}/{{ release_date }}" || true
          tar -xzf /tmp/images.tgz -C "/usr/share/nginx/html/jenkins/tanttws2/app" || true
          rm -f /tmp/images.tgz /tmp/images.tgz.b64
          echo "✅ Images extracted"
        else
          echo "ℹ️ No Images folder locally, skip"
        fi
      ignore_errors: yes

    - name: Rewrite asset URLs in index.html to relative (css/js/images)
      raw: |
        for f in "{{ deploy_dir }}/{{ release_date }}/index.html" "/usr/share/nginx/html/jenkins/tanttws2/app/index.html"; do
          if [ -f "$f" ]; then
            sed -i 's@href="/css/@href="css/@g;s@src="/css/@src="css/@g;s@href="/js/@href="js/@g;s@src="/js/@src="js/@g;s@href="/images/@href="images/@g;s@src="/images/@src="images/@g' "$f" || true
            sed -i "s@href='/css/@href='css/@g;s@src='/css/@src='css/@g;s@href='/js/@href='js/@g;s@src='/js/@src='js/@g;s@href='/images/@href='images/@g;s@src='/images/@src='images/@g" "$f" || true
          fi
        done
      when: copy_result is succeeded
      ignore_errors: yes

    - name: Fallback if index copy failed
      raw: |
        echo "❌ Copy failed, using fallback content"
        cat > "{{ deploy_dir }}/{{ release_date }}/index.html" << 'EOF'
        <!DOCTYPE html>
        <html>
          <head>
            <title>Demo Deploy</title>
          </head>
          <body>
            <h1>Hello World !</h1>
          </body>
        </html>
        EOF
        chmod 644 "{{ deploy_dir }}/{{ release_date }}/index.html"
      when: copy_result is failed

    - name: Update current symlink
      raw: |
        cd "{{ deploy_dir }}"
        if [ -e current ] || [ -L current ]; then
          rm -rf current
        fi
        ln -s "{{ release_date }}" current

    # Display deployment success information
    - name: Display deployment success information
      debug:
        msg:
          - "✅ Remote deployment successful!"
          - "📁 Deploy directory: {{ deploy_dir }}"
          - "📊 Release: {{ release_date }}"
          - "🔗 Current symlink: {{ deploy_dir }}/current"
          - "🌐 Web URL: http://10.1.1.195/jenkins/tanttws2/deploy/current/"